### ISSUE TITLE
Naming of Domain Objects

### ISSUE THREAD

**Issue by Valefant** [OSOSystem/oso-backend#20]
Some points regarding to our domain model which I have noticed.

* The naming of ``ErmengencyType`` is not expressive enough. My suggestion would be ``EmergencyPriority``.
* The same goes with ``EmergencyAction``. My suggestion would be ``EmergencyStatus``. Furthermore I would rename the states into simple past form like ``ACCEPTED`` instead of ``ACCEPT``.

**Comment by VincentDiedrich** [comment]
I'll take care of this issue
