### ISSUE TITLE
Move Paths from Controllers into a single file

### ISSUE THREAD

**Issue by Valefant** [OSOSystem/oso-backend#34]
The current paths are nested in an ``companion object`` within every controller.

For example in the ``HelpProviderController`` we have the following structure
```kotlin
companion object {
    const val PATH_HELP_PROVIDERS = "help-providers"
    const val PATH_HELP_REQUESTERS = "help-requesters"
    const val PATH_ACCEPT_EMERGENCY = "accept-emergency"
}
```

To avoid duplications across all controllers we want to gather them into a single file.
<br>
**Implementation Notes**
The file should be placed in the package ``org.oso.config``.

The resulting structure should have this form
```kotlin
object Paths {
    object Emergency {
        const val ROOT = "emergency"
        const val EMIT = "emit"
        const val ACCEPT = "accept"
    }

    ...
}
```

And then could be used like this
```kotlin
@Controller
@RequestMapping(Paths.Emergency.ROOT)
class EmergencyController
```

**Comment by VincentDiedrich** [comment]
I would like to take care of this issue
