### ISSUE TITLE
Database Migration Scripts

### ISSUE THREAD

**Issue by Valefant** [OSOSystem/oso-backend#4]
To provide initial values, we have to consider using migration scripts.
These scripts should then be executed whenever the application is about to start.

More information can be found under
https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html

**Comment by pwilken** [comment]
Can I close the issue?

[Reason](https://github.com/OSOSystem/oso-backend/issues/26)

**Comment by Valefant** [comment]
Yes we can close this one.
