### ISSUE TITLE
Lock version of docker images

### ISSUE THREAD

**Issue by Valefant** [OSOSystem/oso-backend#7]
We should avoid to pull new image releases from Docker Hub directly.
This can be problematic with Keycloak for instance, as it requires an adapter for Spring, which is not updated automatically.

Most images provide the possibility to lock them on a specific version.
Except for Keycloak where we have to come up with a solution.

**Comment by pwilken** [comment]
We can simply use the version tag instead of the latest tag, for pulling from the docker hub.
[jboss/keycloak/tags/](https://hub.docker.com/r/jboss/keycloak/tags/)

**Comment by Valefant** [comment]
Ups, haven't even noticed that. :sweat_smile: Thanks for the hint.
